# Base de dados de exemplo: páginas e links entre elas
pages = {
    0: {"title": "Python Programming", "content": "Learn programming with Python.", "links": [1, 2, 3, 4]},
    1: {"title": "Data Science", "content": "Data science involves statistics and machine learning.", "links": [2, 5, 6]},
    2: {"title": "Machine Learning", "content": "Explore AI and machine learning with Python.", "links": [0, 3, 7]},
    3: {"title": "Artificial Intelligence", "content": "AI is the future of technology.", "links": [1, 4, 8]},
    4: {"title": "Big Data", "content": "Big Data is transforming industries.", "links": [2, 5, 9]},
    5: {"title": "Statistics", "content": "Statistics is a core skill for data science.", "links": [6, 10]},
    6: {"title": "Algorithms", "content": "Algorithms are the foundation of computer science.", "links": [2, 7, 11]},
    7: {"title": "Deep Learning", "content": "Deep learning is a subset of machine learning.", "links": [3, 8, 12]},
    8: {"title": "Neural Networks", "content": "Neural networks power deep learning.", "links": [7, 9, 13]},
    9: {"title": "Data Engineering", "content": "Data engineering is essential for data pipelines.", "links": [4, 10, 14]},
    10: {"title": "Mathematics for AI", "content": "Mathematics is the foundation of AI.", "links": [11, 15]},
    11: {"title": "Probability", "content": "Probability theory is key in statistics.", "links": [10, 12, 16]},
    12: {"title": "Computer Vision", "content": "Computer vision allows machines to see.", "links": [8, 13, 17]},
    13: {"title": "Natural Language Processing", "content": "NLP is about understanding human language.", "links": [12, 14, 18]},
    14: {"title": "Data Visualization", "content": "Data visualization is crucial for insights.", "links": [9, 15, 19]},
    15: {"title": "Linear Algebra", "content": "Linear algebra is used in machine learning.", "links": [10, 16, 20]},
    16: {"title": "Calculus", "content": "Calculus is fundamental for modeling change.", "links": [11, 17, 21]},
    17: {"title": "Optimization", "content": "Optimization is used in machine learning models.", "links": [12, 18, 22]},
    18: {"title": "Speech Recognition", "content": "Speech recognition allows voice-controlled systems.", "links": [13, 19, 23]},
    19: {"title": "Cloud Computing", "content": "Cloud computing enables scalable resources.", "links": [14, 20, 24]},
    20: {"title": "Quantum Computing", "content": "Quantum computing is the future of computation.", "links": [15, 21, 25]},
    21: {"title": "Cryptography", "content": "Cryptography secures communication.", "links": [16, 22, 26]},
    22: {"title": "Blockchain", "content": "Blockchain is a distributed ledger.", "links": [17, 23, 27]},
    23: {"title": "Cybersecurity", "content": "Cybersecurity protects data and systems.", "links": [18, 24, 28]},
    24: {"title": "Networking", "content": "Networking connects devices and systems.", "links": [19, 25, 29]},
    25: {"title": "Software Development", "content": "Software development involves coding and design.", "links": [20, 26, 30]},
    26: {"title": "Operating Systems", "content": "Operating systems manage hardware and software.", "links": [21, 27, 31]},
    27: {"title": "Embedded Systems", "content": "Embedded systems are used in IoT.", "links": [22, 28, 32]},
    28: {"title": "Internet of Things", "content": "IoT connects devices over the internet.", "links": [23, 29, 33]},
    29: {"title": "Virtual Reality", "content": "VR creates immersive experiences.", "links": [24, 30, 34]},
    30: {"title": "Augmented Reality", "content": "AR overlays digital content onto reality.", "links": [25, 31, 35]},
    31: {"title": "Human-Computer Interaction", "content": "HCI studies the interaction between people and computers.", "links": [26, 32]},
    32: {"title": "Robotics", "content": "Robotics involves designing intelligent machines.", "links": [27, 33]},
    33: {"title": "Autonomous Vehicles", "content": "Autonomous vehicles can drive themselves.", "links": [28, 34]},
    34: {"title": "3D Printing", "content": "3D printing creates physical objects from digital designs.", "links": [29, 35]},
    35: {"title": "Genomics", "content": "Genomics studies the genome and its functions.", "links": [30, 0]}
}
